### ISSUE TITLE
How do you call functions that expect a Ctypes.ptr?

### ISSUE THREAD

**Issue by TyOverby** [tjammer/raylib-ocaml#18]
I want to call `draw_line_strip` which has type `Raylib.Vector2.t Ctypes.ptr`, but unless I'm missing something, it's impossible to build a CArray of vector2 with the API at present.

**Comment by tjammer** [comment]
Hi again,
I've finally updated the bindings to include the type value in every module, https://github.com/tjammer/raylib-ocaml/blob/master/src/raylib/raylib.mli#L430
