### ISSUE TITLE
raygui package in opam is outdated

### ISSUE THREAD

**Issue by MarcdeFalco** [tjammer/raylib-ocaml#24]
Hi, it seems raygui package wasn't updated on opam as it's linked to raylib 0.3.2 while raylib latest version is more recent.

**Comment by tjammer** [comment]
You're right. For some reason I didn't upgrade the raygui package since no work was added there. I should have realized that the versions clash. I will push a 0.5.1 version to opam, matching the current raylib version

**Comment by tjammer** [comment]
I have created the PR https://github.com/ocaml/opam-repository/pull/21268

**Comment by tjammer** [comment]
PR is merged :)
