### ISSUE TITLE
Creating image from memory

### ISSUE THREAD

**Issue by linsyking** [tjammer/raylib-ocaml#33]
I want to load an image from memory, but I cannot find a function to create an image.

Equivalent in C:

```c
Image img                          = {0};
img.format                         = PIXELFORMAT_UNCOMPRESSED_R8G8B8;
img.mipmaps                        = 1;
img.width  =1920;
img.height = 1080;
img.data   = malloc(img.width * img.height * 3);
```

**Comment by linsyking** [comment]
Or how to create texture with given format and size?

**Comment by tjammer** [comment]
There's [load_image_from_memory](https://tjammer.github.io/raylib-ocaml/raylib/Raylib/index.html#val-load_image_from_memory), where the image data is provided as an ocaml string.
From there, you could use [load_texture_from_image](https://tjammer.github.io/raylib-ocaml/raylib/Raylib/index.html#val-load_texture_from_image). I have never used these functions, so please report back if something is not working.

The texture struct isn't exposed for writing right now. I think the data field isn't exposed at all.

**Comment by linsyking** [comment]
> There's [load_image_from_memory](https://tjammer.github.io/raylib-ocaml/raylib/Raylib/index.html#val-load_image_from_memory), where the image data is provided as an ocaml string. From there, you could use [load_texture_from_image](https://tjammer.github.io/raylib-ocaml/raylib/Raylib/index.html#val-load_texture_from_image). I have never used these functions, so please report back if something is not working.
> 
> The texture struct isn't exposed for writing right now. I think the data field isn't exposed at all.

From [this issue](https://github.com/raysan5/raylib/issues/2372#issue-1160573783), if i want to use rlgl then I need a texture constructor.

**Comment by linsyking** [comment]
> > From [this issue](https://github.com/raysan5/raylib/issues/2372#issue-1160573783), if i want to use rlgl then I need a texture constructor.
> 
> In the linked issue, they want to fill the texture struct directly. The issue they are having is the texture id, which needs access to GL to generate (through rlgl here). The function `load_texture_from_image` sets it correctly though, see here https://github.com/raysan5/raylib/blob/5e1a81555ca130e2c6544add0e2391a8763e7e2a/src/rtextures.c#L3340. So the way of creating an image and then a texture should work.
> 
> The lowlevel rlgl function is also exposed by the bindings (https://tjammer.github.io/raylib-ocaml/raylib/Raylib/Rlgl/index.html#val-load_texture), but as I said, the texture struct isn't writable from the ocaml side directly

Thanks for your help!

The problem with `load_texture_from_image` is that I cannot set the image format (e.g. `PIXELFORMAT_UNCOMPRESSED_R8G8B8`), so it becomes impossible to load some image correctly.

Also the image data is binary data so I think it should be pointer type rather than string.

**Comment by tjammer** [comment]
Yes, you're right about the image format.
I'll expose the missing fields of Texture then and make them writable. That way one can use exactly the same method as one would in C.
It'll take a few days because the rlgl bindings are pretty raw. One of those int from [load_texture](https://tjammer.github.io/raylib-ocaml/raylib/Raylib/Rlgl/index.html#val-load_texture) shoulde be the image format, for instance.

Regarding binary data; String in OCaml are just arrays of bytes so they could be used that way. I'd be clearer to have something like Bytes.t instead, I agree

**Comment by tjammer** [comment]
I've added a [create function](https://github.com/tjammer/raylib-ocaml/blob/master/src/raylib/raylib.mli#L748) to the Textures module that you can use like in the raylib issue above.
The[ rlgl function](https://github.com/tjammer/raylib-ocaml/blob/master/src/raylib/rlgl.mli#L103) doesn't take a `PixelFormat.t` right now as the pixel format, but an int. To call it, you need to use `Pixelformat.to_int`.
