### ISSUE TITLE
`Raylib.get_char_pressed` has wrong type

### ISSUE THREAD

**Issue by gravicappa** [tjammer/raylib-ocaml#35]
As far as I understand `Raylib.get_char_pressed` should have type `unit -> int`(or `unit -> Uchar.t`) instead of `unit -> Raylib.Key.t` since it returns unicode code point.

**Comment by tjammer** [comment]
Hi, thanks for reporting this!
Your understanding is correct, this is already fixed on master, see https://github.com/tjammer/raylib-ocaml/issues/34.
The change hasn't made it into a release on opam yet, so you have to pin the master branch with opam.

I'll prepare a release to opam soon to distribute this fix
