### ISSUE TITLE
Bindings for Raymath functions

### ISSUE THREAD

**Issue by Lattay** [tjammer/raylib-ocaml#4]
Related to #3 I quickly stumbled into a problem.
I wanted to implement core_2d_camera_platformer but the C version uses Vector2* functions from Raymath and I think it is the best way to do it.
In my opinion it would be nice to add those functions inside the Raylib.Vector2 module (and do something similar for the rest of Raymath) so that we would have the possibility to call Vector2.length for example.

What do you think ?

I can do it eventually but I never made C binding myself so I don't know the tools, or even where to starts.

**Comment by tjammer** [comment]
I don't see anything which blocks the addition tbh. The only reason I chose not the add bindings for these functions was that I was lazy, and I suspected people would rather use something like [GG](https://erratique.ch/software/gg/doc/Gg.html) which is purely OCaml.

I will get on it

**Comment by tjammer** [comment]
Hi Lattay,

I added the raymath functions to the vector types like you suggested.
The only exceptions to this are the `to_float_v` functions, because it wasn't immediately obvious what to return (probably a CArray.t).

I haven't tested them yet and will leave the ticket open until they have seen at least some usage, either by you or me

**Comment by Lattay** [comment]
Hi,
About GG, I did not know about it, I though including Raymath is useful because objects are in C representation so it is probably slightly more efficienty to use the C functions, I think those simple functions are use a lot when you manipulate vectors so constant OCaml <-> C exchanges would probably be somewhat inneficient.
As for to_float_v I don't think it make much sens to bind it, such a type conversion function could be written in pure OCaml and return a native OCaml Array for example.

Thank you for bindings this, I already partially wrote a core example that uses them, I'll tell you here if anything goes wrong.

**Comment by tjammer** [comment]
I definitively agree that these functions are useful to have. About efficiency I'm not 100% sure, b/c ctypes does not yet allow automatic unboxing and thus there is more overhead than needs to be whenever a C function is called. Most likely it does not matter ;)

I think one use-case for to_float_v could be setting uniforms in raylib. I'm not sure if you can use native OCaml arrays there. Anyway, it's not super high prio
