### ISSUE TITLE
Raygui.text_box appends unwanted '0' bytes to result

### ISSUE THREAD

**Issue by kevinclancy** [tjammer/raylib-ocaml#46]
When I call `Raygui.text_box bounds text edit_mode` the result will append the byte `0` onto `text` even if no key has been pressed. I can work around this by trimming 0's off the result. 

Also, the doc comment suggests there is is a `text_size` argument, which `text_box` doesn't actually have.

**Comment by tjammer** [comment]
It's even worse than you say, a null byte is added on each frame and the string length grows and grows. Ouch!

The doc comments were copied from raylib, which has the extra `text_size` parameter.

**Comment by tjammer** [comment]
The fix is on master now. I'll leave the issue open until I pushed a new release to the opam repo
