### ISSUE TITLE
Consider supporting dune 3.0

### ISSUE THREAD

**Issue by gpetiot** [tjammer/raylib-ocaml#53]
Dune 3.0 has been released in 2022, it would be nice to progressively catch up with the latest releases to benefit from recent features.

For example, from the dune docs: https://dune.readthedocs.io/en/stable/foreign-code.html#stub-generation-with-dune-ctypes
> Beginning in Dune 3.0, it’s possible to use the [ctypes](https://github.com/ocamllabs/ocaml-ctypes) field to generate bindings for C libraries without writing any C code.

The file https://github.com/tjammer/raylib-ocaml/blob/master/src/c/dune needs to be modified (we get some errors like `Error: The form %{lib:<libname>:.} is no longer supported since version 3.0`) but it should be a net improvement.

**Comment by tjammer** [comment]
I'm not against it, I just didn't have time to do the update yet and the current solution works quite well.

When I first read about the ctypes integration I was afraid that I had to re-do the structure of the bindings quite a bit.

**Comment by tjammer** [comment]
Done, at last

**Comment by gpetiot** [comment]
Awesome, thanks!
