### ISSUE TITLE
Switch on FLAC support

### ISSUE THREAD

**Issue by rossberg** [tjammer/raylib-ocaml#57]
For some odd reason, upstream Raylib has FLAC support turned off by default. Could we switch it on for the OCaml package, analogous to JPEG?

Ideally, that should only require setting `SUPPORT_FILEFORMAT_FLAC` as a [build option](https://github.com/raysan5/raylib/wiki/CMake-Build-Options), though I am not sure what dependencies are involved.

**Comment by rossberg** [comment]
Wow, that was fast, thanks! Are you planning to make a new opam release anytime soon?

**Comment by tjammer** [comment]
I'm in the process of upgrading the bindings to dune 3 right now. Once this is done, I'll release to opam

**Comment by rossberg** [comment]
Splendid, thanks!
