### ISSUE TITLE
[Bug] Wrong type for some Key related functions

### ISSUE THREAD

**Issue by Lattay** [tjammer/raylib-ocaml#6]
Some functions declared in `raylib/src/camera.h` are declared to take an `int` parameter in OCaml while they should take a `Raylib_generated_constants.Key.t` parameter just like is_key_down and friends.
Functions I spotted are the following:

```C
void SetCameraPanControl(int panKey);                       // Set camera pan key to combine with mouse movement (free camera)
void SetCameraAltControl(int altKey);                       // Set camera alt key to combine with mouse movement (free camera)
void SetCameraSmoothZoomControl(int szoomKey);              // Set camera smooth zoom key to combine with mouse (free camera)
void SetCameraMoveControls(int frontKey, int backKey,
                           int rightKey, int leftKey,
                           int upKey, int downKey);         // Set camera move controls (1st person and 3rd person cameras)
```

**Comment by Lattay** [comment]
I see that it is defined in `src/c/functions/raylib_functions.ml` but is this a generated file ?
Or should I modify it by hand ?

**Comment by tjammer** [comment]
Nice catch!
You can modify the file, I generated it at the start once but since then edited it.
